# Generated by Django 4.2.16 on 2024-09-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sp', models.FloatField()),
                ('dp', models.FloatField()),
                ('desc', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('categoty', models.CharField(choices=[('BS', 'Barik Sev'), ('MS', 'Moti Sev'), ('CD', 'Chana Dal'), ('CB', 'Chatpati Boondi')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
